apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "php-fpm"
  template:
    metadata:
      labels:
        app: "php-fpm"
    spec:
      initContainers:
        - name: check-db
          image: busybox:1.28
          # Проверяем, что запустился контейнер и сервис mysql
          command: ['sh', '-c', 'until nc -z mysql 3306; do sleep 2; done']
      containers:
      - image: "phpprogrammist/php:8.1-fpm-dev-mysql"
        name: php-fpm
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/php/conf.d/local.ini
          subPath: local.ini
        - name: core-storage
          mountPath: /var/www/html
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      volumes:
        - name: config-volume
          configMap:
            name: php-config
        - name: core-storage
          hostPath:
            path: /opt/docker-lessons/level7/lemp/step2/core # абсолютный путь на хост-машине к папке с файлами приложения
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: php-fpm
spec:
  type: ClusterIP
  selector:
    app: php-fpm
  ports:
    - port: 9000 # Порт, который слушает сервис
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: php-config
data:
    local.ini: |
      upload_max_filesize=40M
      post_max_size=40M
      display_errors=1
      display_startup_errors=1
      error_reporting=E_ALL
