version: "3.9" # Версия синтаксиса файла

services: # Сервис - это некая обертка над контейнером.
    # Эта задача, которая создает один или несколько контейнеров и контролирует их состояние.
    # В большинстве команд используются именно названия сервисов, а не контейнеров.
    db: # Название сервиса. Оно используется для автоматического определения IP сервиса, а также в секции "depends_on"
        image: mysql:8.0 # Название образа
        environment: # Переменные окружения
            - MYSQL_ROOT_PASSWORD=lemp-pass
            - MYSQL_DATABASE=lemp-db
        volumes: #Тома. Именованный Docker том "db_volume" нужно обязательно указать в корневом элементе "volumes" (в конце файла)
            - db_volume:/var/lib/mysql # Сокращенная запись для Volume mount.
            #Сначала указано название тома, а после двоеточия - абсолютный путь в контейнере

    php-fpm: # Название сервиса.
        image: phpprogrammist/php:8.1-fpm-dev-mysql
        volumes:
            - ./config/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./core:/var/www/html # Сокращенная запись для Bind mount.
            #Сначала указан относительный путь на хост-машине, а после двоеточия - абсолютный путь в контейнере
        depends_on: # Зависимости сервиса. Данный сервис будет запущен после запуска сервиса "db"
            - db

    edge: # Название сервиса.
        image: nginx:1.23-alpine
        ports:
            - '8000:80' # Сокращенная запись маппинга портов.
            # Сначала указывается порт хост-машины, а после двоеточия - порт контейнера.
        volumes:
            - ./config/edge/nginx.conf:/etc/nginx/nginx.conf
            - ./config/edge/php.conf:/etc/nginx/conf.d/php.conf
            - ./core:/var/www/html
        depends_on: # Зависимости сервиса. Данный сервис будет запущен после запуска сервиса "php-fpm"
            - php-fpm

volumes: # Именованные Docker тома, которые используются в сервисах, должны быть перечислены здесь
    db_volume: