apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "php-fpm"
  template:
    metadata:
      labels:
        app: "php-fpm"
    spec:
      containers:
      - image: "php:fpm-alpine"
        name: php-fpm
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/php/conf.d/php.ini # Монтируем файл настроек PHP
          subPath: php.ini
        - name: core-storage
          mountPath: /var/www/html # Путь внутри контейнера, куда будут записаны файла приложения
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
      volumes:
        - name: config-volume
          configMap:
            name: php-config
        - name: core-storage
          hostPath:
            path: /opt/docker-lessons/level7/lemp/step1/core # абсолютный путь на хост-машине к папке с файлами приложения
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm # По этому имени сервис доступен во внутренней сети - php-fpm:9000
  labels:
    app: php-fpm
spec:
  type: ClusterIP
  selector:
    app: php-fpm
  ports:
    - port: 9000 # Порт, который слушает сервис
      # targetPort: 9000 # Порт контейнера. Т.к. порт сервиса и порт контейнера совпадают, то targetPort можно не указывать.
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: php-config
data:
    local.ini: |
      upload_max_filesize=40M
      post_max_size=40M
